# -*- coding: utf-8 -*-
"""Python_projct2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKTnxVoTou4FOxZY1WmBoax6GTPFwxN1
"""

import time
from datetime import datetime

bus_schedules = [
    {"name": "Express 1", "timings": ["08:00", "12:00"], "route": ["Bangalore", "Mysore", "Coorg"]},
    {"name": "Rapid 2", "timings": ["10:00", "14:00"], "route": ["Bangalore", "Chennai", "Madurai"]}
]

def get_buses_by_time(desired_time):
    available_buses = []
    for bus in bus_schedules:
        for timing in bus["timings"]:
            if timing == desired_time:
                available_buses.append(bus)
    return available_buses

def get_buses_by_route(desired_route):
    available_buses = []
    for bus in bus_schedules:
        if desired_route in bus["route"]:
            available_buses.append(bus)
    return available_buses

def get_buses_by_time_and_route(desired_time, desired_route):
    available_buses = []
    for bus in bus_schedules:
        if desired_time in bus["timings"] and desired_route in bus["route"]:
            available_buses.append(bus)
    return available_buses

def get_buses_by_date(desired_date):
    available_buses = []
    for bus in bus_schedules:
        for timing in bus["timings"]:
            bus_time = datetime.strptime(timing, "%H:%M")
            if bus_time.date() == desired_date:
                available_buses.append(bus)
    return available_buses

def print_bus_details(buses):
    if buses:
        for bus in buses:
            print(f"Bus Name: {bus['name']}")
            print("Timings:")
            for timing in bus["timings"]:
                print(f"- {timing}")
            print("Route:")
            for stop in bus["route"]:
                print(f"- {stop}")
    else:
        print("No buses available for the specified criteria.")

# Example usage:
desired_date_str = input("Enter desired date (YYYY-MM-DD): ")
desired_time = input("Enter desired time (HH:MM): ")
desired_route = input("Enter desired route (e.g., Bangalore to Mysore): ")

desired_date = datetime.strptime(desired_date_str, "%Y-%m-%d")

# Get buses based on time, route, and date
buses = get_buses_by_time_and_route(desired_time, desired_route)
buses = [bus for bus in buses if bus_time.date() == desired_date]

print_bus_details(buses)